# Short Sheets {-}

The following sections contain "Short Sheets", which are bullet pointed lists with links to more comprehensive information. The impetus for these "Short Sheets" came from wanting to find a way to present the right information to our students, at the right time in their career. Instead of simply creating another collection of dense information, the "Short Sheets" are essentially checklists (inspired, in-part, [by the Checklist Manifesto](http://atulgawande.com/book/the-checklist-manifesto/)) that also link to more dense information. If you can safely "check off" a bullet point, saying to yourself *done that* or *I know about that*, then feel free to move past that point. If you'd like our peer input on that bullet point, read it fully and follow the links as way to get started. Remember to make time and check back for the Short Sheet most relevant to your current stage of training. Also, be mindful that not all the information in the book is linked up to a bullet point somewhere (esspecially information in the appendicies)!

## M1: Pre-matriculation {-}

**Please note that it is virtually impossible to list out all the things that you need to do before matriculating to the medical school. For the most part, the medical school and MSTP program will guide you through this process. Highlighted here are resources for aspects of the transition that people usually need help with and do not always have a guide for.**

### Things to Do {-}

- **Find a place to live:** [The Medical School’s Student-To-Student  Guide p. 34](https://www.urmc.rochester.edu/MediaLibraries/URMCMedia/education/md/documents/bluebook.pdf) has a fantastic section detailing housing. Also, read our quick blurb on [a general format for finding a place to live](#very-general-guidance-on-finding-a-place-to-live).

- **Decide on a summer rotation:** Rotations in the summer before entering medical school [are optional (paragraph 1)](https://www.urmc.rochester.edu/education/md-phd/students/student-handbook/curriculum/year-one.aspx). Read our section on [what to consider for an incoming rotation](#inc_rot) if you would like our peer perspective on this choice.

- **Get an understanding of how [taxes](#taxes) work** as a graduate or MSTP student at URMC. Particularly, it is important to understand whether you will need to save a portion of your paychecks to [pay extra taxes at the end of your transition year.](#the-incoming-hiccup)

### Things to Consider {-}

- **Read the description of [Year One](https://www.urmc.rochester.edu/education/md-phd/students/student-handbook/curriculum/year-one.aspx)** in the MSTP student handbook to get a general sense of what is coming at you this year.

- **You will want to plan to move in earlier than the weekend before medical school orientation**. The MSTP program typically has a picinc and retreat on Thursday and Friday before 1st years start. **The 2019 MSTP Picnic is on Thursday, August 8th** after work at the [Hawthorne Shelter in GVP](https://www.google.com/maps/place/Hawthorne+Shelter/@43.1165978,-77.6382423,15z/data=!4m5!3m4!1s0x0:0xf7eb90be0d581294!8m2!3d43.1165978!4d-77.6382423).

- **There are good disussions about Parking (p. 48), Restaurants (p. 72), and Bars (p. 81) in the [Medical School Student-to-Student Guide.](https://www.urmc.rochester.edu/MediaLibraries/URMCMedia/education/md/documents/bluebook.pdf)**

### What if? {-}
## M1: May {-}
## M2: August {-}
## M2: December {-}
## M2: April {-}
