# Early Medical Years {-}

## Transitioning to Rochester {-}

### Very general guidance on finding a place to live {-}

*Author: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu)*

Being a medical student requires a workflow that demands a lot of your time and energy. As such, even generally short commutes or coordinating a complex parking situation can become a thorn in your side on heavy studying days. Being able to sleep in a bit or walk to the library can really make a difference when you're pulling long days.

Because of this, it is generally recommended that incoming students find a place close to the University for the first year in the program. Since you'll be spending 7-9 years here, using the first year to hammer down your medical school workflow and get a feel for Rochester is a good investment of your time. For single people, this tends to manifest as getting a room/splitting a house in the White Coat area or getting a room in Goler House. For couples, getting an apartment at University Apartments or one of the many apartment complexes nearby is a solid choice.

One "transitional" year can really pay off in the long run. Even if you end up wanting to move farther from the University, the one year spent getting your footing and exploring the variety of neighborhoods in Rochester allows you to get the most out of your housing situation in the back 6-8 years without putting to much stress on you at the transition point.

### To do or not to do; an incoming rotation... {-#inc_rot}

*Author: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu)*

This is an age old question that many a-incoming MSTPer struggles with. For most, it is a battle within one's self that hinges upon a much simpler, practical question:

> *Do I keep working, or do I take a break?*

Realistically, only you can answer this question for yourself; however, there are a few key points that you should consider when making this decision.

#### *The rotation is truly optional* {-}

Seriously, [check it](https://www.urmc.rochester.edu/education/md-phd/students/student-handbook/curriculum/year-one.aspx). It is optional from a policy stand-point. It is optional from a social stand-point. Many of our students do this rotation and many do not, but the unifying factor is that we all understand that it is a personal choice.

#### *It will only impact your career here if you want it to* {-}

There are plenty of students who pass on this rotation. At our regular end-of-the-year panel discussion, where our graduating students pass down wisdom to our younger years, no one (in recent memory) has cited their incoming rotation as a particularly pertinent element of their career. That being said, there are plenty of students that have used this first rotation to get a jump on their research, especially when they rotated with a PI that they have a pre-established relationship with. While medical school typically consumes most of your time, there have been students who engaged with research during the medical school years and felt that they really benefitted from this. The bottom line is that this rotation could help you advance your research interests if you invest in that, but skipping is not a hindrance to your training.

#### *You get paid while you are here* {-}

This is as straightforward as can be; you're starting your ~~job~~ training earlier and you're getting paid earlier. If ever there was a clearer reason to work instead of take a break, it is this one.

#### *The incoming summer is one of the last true breaks for a long time* {-}

Especially for those transitioning directly from a college or masters program, the time between graduating and starting your medical training is too short to start up new projects but long enough to have a lot of fun. For most, this period of time represents one of the last, if not *the* last time, that you spend more than a few weeks away from all the projects, studying, writing, etc. that comes with the dual career. You will be required to do a rotation between the M1 and M2 summer. M2 summer will have you invested in STEP studying and then you join another rotation or rejoin your lab. In graduate school, there is always another paper to read, manuscript to revise, abstract to write, or emails to send. M3 and M4 won't respect any sense of summer boundaries. This is not to say that you won't find time for a vacation, but few people have ever found a 2+ month period where they were not beholden to career commitments during their MSTP training. Many students choose to do some traveling, see family, and/or take time with a significant other during this time.

#### *A general recommendation* {-}

Returning to our simplified question, *do I keep working, or do I take a break?*, one can only make a solid recommendation to those on the extreme ends:

- **If you are a current college senior, having interviewed while finishing college, the general recommendation from almost all of your peers is that you take the summer off before starting medical school.**
- If you ended a job early, got your share of travel/seeing family well before school starts, and don't have much else to do - get moving on a rotation!

Beyond these scenarios, you'll get a mix of advice and you will have to figure out what is applicable to you. You should always feel free to contact any of our MSTP students for advice or input - an editor of this book would happily speak with you if you reached out. If you find yourself truly unable to decide, flip a coin. If you don't the result, pretend it landed on the other side.

## Advice for Courses {-}

### HSF {-}

*Authors: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu), [Alison Livada](mailto:alison_roby@urmc.rochester.edu), and the MSTP Class of 2026*

[The Medical School’s Student-To-Student Guide p. 8](https://www.urmc.rochester.edu/MediaLibraries/URMCMedia/education/md/documents/bluebook.pdf) has great information about specific details about the Human Structure Function (HSF) course. Everything from textbook recommendations to a subject-by-subject breakdown of study strategy is present here. It is highly recommended that you at least skim this section to understand what advice you could read, should you need some specific input. Here, our MSTP students would like to express their general advice about approaching HSF. 

**Get your life together before starting HSF:** Thanks to some recent curricular changes, 1st year medical students start their career here in *arguably* the most demanding course URMC has to offer. As such, it's pretty imperative that first years quickly develop a routine that can keep them afloat. Ideally, in the few weeks before starting HSF, an incoming student should get into a routine where they are **working 10 hours/day for 5-6 days a week, awake and active during from 8am-5pm every day, with your workouts, sleeping, cooking, etc. happening outside the 8am-5pm spot.** This does not mean that every day, or every week of HSF, will be like this. However, getting yourself adapted prior to entering HSF will allow you to quickly find the right routine for you without falling behind on work (e.g. sleeping through early lectures or not having enough energy to stay attentive through the day early on).

**Be immersed in HSF:** HSF is an intense course for students and teachers. Some people have estimated that it is, within itself, enough credit hours for the average college major. It is a crowning course of this institution and many regard it as the hardest thing that you will do at Rochester. This course is where you learn human physiology in amazing depth. It is very demanding but incredibly rewarding if you pay attention and learn as much as you can. What you learn in this course forms the foundation for all the other knowledge you take in during medical school. Literally, everything you study for this course has the potential to benefit a patient you will see in the future. So when you’re sitting there, racking your brain, asking yourself why you need to know such minutia, please trust that it will be worth it down the line. A number of people make HSF harder for themselves by thinking "is this what medical school will always be like?", "will I always be this tired?",  or "will I ever get time for my hobbies or interests again?". The answers are "no", "no", and "yes", respectively. Try to put those worries out of your mind and trust that the most efficient, time-tested way to get all this information in your head is to cut out a few months and really focus. Additionally, this is one of the few times in your life where you will have so many dedicated teachers at your disposal, ready to help you learn as much as you can. As such, use this period of time as an incredibly privileged learning opportunity and trust that life will balance out afterward. 

**Try hard, but don't be hard on yourself:** Your first two years of medical school are indeed pass/fail. However, our older students would like to emphasize **that HSF too is pass/fail**. Given that this is the first course, it can be challenging to adopt the pass/fail perspective after whatever your rigorous journey was to medical school. We believe that focusing on passing and being comfortable with not knowing all the material will be a useful tool in maintaining physical and mental wellness in the context of a long MSTP program. Some of your MD peers might be focusing on top 10 percent or acing STEP already during the first year in preparation for competitive residency applications. As MSTP students, the PhD puts more time between your pre-clinical years and your residency applications, giving you time to develop and bring your unique assets to the residency process. As such, pushing yourself too hard, early on in your journey is likely to hurt more than it will help. You will be challenged throughout the MSTP and there is no need to set a higher bar for yourself, as some of us may be want to do.

### SRM {-}

### MMI {-}

### MTC {-}

### Host Defense {-}

### Pharmacology {-}

### MBB {-}

### DPT {-}