# Pre-Qualification {-}

Here, we cover topics related to roughly the first two years of graduation, where the main objective is to produce a project for your thesis work. For the vast majority of people in this program, this project will also be subitted to the NIH in the form of a grant (an F30). 

## Finding a Mentor {-}

*Author: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu) and [Udaysankar Chockanathan](mailto:udaysankar_chockanathan@urmc.rochester.edu)*

### Introduction {-}

When I was searching for a lab to do my PhD in, I was really focused on what ideas and techniques were most interesting to me. What I\'ve learned is that the process of pursuing your ideas requires, first and foremost, **support**. Someone needs to pay for the equipment you use, teach you or sponsor your acquisition of technical skills, sign-off on your publications and grants, and believe in you as a scientist. Without these things, even the most innovative projects remain only as ideas.* -Reflection from an MSTP Student.

We\'re willing to put these quotes down to remind ourselves, and hopefully teach others, that one\'s mentor is a critical determinant of success in graduate school. As such, all students should put genuine effort into assessing a potential mentor. We hope to use the following points to ground your thinking and aid your decision making in the search for a lab and mentor. As expected, it all starts with a rotation (Part I), for which we suggest a few critical things that you should consider when deciding to rotate and things to observe while you rotate. Formally joining a lab (Part II) is, essentially, a more thorough execution of the principles from Part I. While following through with these points may, at times, feel like a chore, getting this information and having these conversations will help you avoid the most common troubles that are reported in a mentor-mentee relationship. **If you do nothing else, at least read what\'s bolded.** Now... before we start, it is important to keep something in mind:

### There is No Perfect Lab or Perfect Mentor {-}

If you look hard at any lab or any person, you will find aspects of them that you admire and aspects that you dislike. A lab that is a good fit for your friend might not be a good fit for you. The purpose of our following suggestions is not to "dig up dirt" on labs or mentors, but rather to encourage you to get a rich set of information from which to make a decision. Every lab has positives and negatives, and you should do your best to learn about both before joining. Any one individual or source of information is likely to have biases or incomplete information; however, by collecting and integrating information from multiple sources, you should be able to form a more complete picture of the environment that you are joining.

### Part I: Rotating {-}

As you would expect, meeting with a PI (after you have read some papers and gauged your general interest in their lab) is the best first step in making a decision about rotations. **As such, if you\'re interested in a lab, you should schedule a meeting to talk about your interests ASAP**. **Additionally, you should have a face-to-face conversation with at least one other lab member (post doc, graduate student, etc.) prior to making any commitments for rotating**. Aside from the standard set of topics (papers, goals, vision for a PhD/career), you should get answers to the following questions across both meetings:

-  **Will the lab have money to take on a graduate student during the time you are there?** You are most likely looking for a lab to call home (as opposed to scoping out a collaborator), which means that anyone you\'re rotating with should either have the money to take on another student or be willing to write necessary grants. Without funding, it\'s game over no matter how well you do or how well you fit in. In our experience, most mentors are honest about whether they have funding to take a student. If they are not sure about their future funding situation, the past is a good indicator; use [[NIH RePORT]{.underline}](https://report.nih.gov/), [[NSF Award Search]{.underline}](https://www.nsf.gov/awardsearch/), or ask for their Biosketch to see their funding history. In general, PIs should have a history of continuous funding (ideally from an R01) and have a history of intramural grants at University of Rochester, indicating the ability to compete for and maintain funding. Of course, you may feel underqualified to assess a PIs funding situation. If so, we suggest you reach out to Dr. O\'Banion, as he is clearly an ideal resource for this topic.

-   **What is their schedule like?** We highly suggest getting an understanding of what your prospective mentor's day to day schedule is like, how many hours per week they spend in the lab, and what their typical workflow is across a week (when do they like to meet, etc.). One cannot simply make cutoffs for how many hours are acceptable or not, but having a mentor available to weigh in on issues/troubleshooting is critical to success in graduate school. Thus your prospective mentor\'s planned schedule should support that idea.

-   **Who in the lab can tell you about what it\'s like to work there?** Be quick to get a conversation with someone in the lab you\'d like to rotate in - [an earnest, sit down conversation where you get to know a bit about the person you are talking to and they get to know you as well]{.underline}. You want to understand both what is good and not-so-good about working for this PI, as well as what kind of people thrive in their lab. While you\'re always free to ask such questions outright, having a conversation with someone you might be working with usually lends more insight on this matter.

While rotating in a laboratory, pay attention to the following aspects of your experience:

-   **Was the PI accurate when quoting their schedule? Are they or other students/postdocs available to help you?** Anytime someone quotes you their schedule - take it with a grain of salt. All people (except, notably, moms with young children) are horrible at time management. That\'s ok. But it is important that more experienced colleagues are available to help you learn. While being left on your own gives you an inflated sense of responsibility and stature, the feeling fades quickly once you hit a major sticking point anywhere in your workflow.

-   **Are you excited to do the work?** This is not a theoretical question; it is fundamentally a practical one. In theory, we all love ice cream and are happy to try a new flavor that someone else made. However, less than 0.1% of people who love ice cream enjoy the process of making it <sup>Citation needed</sup>.There is a difference between enjoying the result and enjoying the process. You don\'t have to enjoy every aspect of the research process in your rotation lab; however, you should find some joy in the core, day-to-day research tasks that you conduct in the lab. If this is not the case, you\'re better off reading the papers from this lab than writing them yourself.

-   **How is your prospective mentor\'s workflow?** Do they respond to emails? If you or other graduate students need paperwork passed in/recommendations written, does it get done? Do they get documents back to you before a key deadline? Everyone needs deadline reminders and help with forms. However, it is critical that your PI be attentive and responsive to the \"small things\" and not simply dismiss them. This world runs on paperwork and the least dignified way to lose a grant, travel award, or job opportunity is to not get the paperwork done in time.

-   **What is their writing process like?** Do they help you with outlining or idea development? Do they take your feedback on drafts? Do you take their feedback? How do they assign authorship/give credit for work? Ideally, you and your mentor should have compatible styles of reading, writing, and thinking about topics. At the very least, you should be able to politely give and take input while developing a draft. Writing a paper or a grant is where the rubber hits the road for the mentor-mentee relationship and it is highly advised that you do some sort of writing (rotation report, mini-review, portion of a paper, grant contribution, etc.) with your prospective mentor to get insight into this. **Another thing to ask for is a successful recent grant application from their lab.** This not only provides you insight into research projects in the lab, but also the way the mentor thinks and writes about scientific questions.

-   **Do they give constructive/useful feedback on presentations?** Are they tolerant of different styles? Are they present for practice presentations and helpful through the talk development process? Presenting your work to a live, studio audience is another critical aspect of graduate school and another arena in which the mentor-mentee relationship requires robust, bi-directional communication. Like the point before, it is highly advised that you are able to incorporate your prospective mentors input and style suggestions gracefully into your presentations.

### Part II: Choosing A Mentor {-}

Once you have completed your rotations and are deciding on your mentor, we suggest that you consider the following questions and do the following:

-   **Does your prospective mentor have experience graduating MSTP students? If not, would they be willing to do a co-mentorship with someone who does?** Our MSTP students typically spend fewer years in the graduate school, have more frequent committee meetings, have concurrent clinical commitments with their graduate training, and will soon have expedited requirements for writing an F30. Working with an MSTP student requires some advanced knowledge and acceptance of these differences, in order to efficiently fulfill a variety of requirements. As such, **it\'s best that your PI has experience with these demands or accepts input from a PI that has graduated MSTP students**. A co-mentorship does not need to entail that you are financially supported by two PIs or work in two labs. Rather, establishing a common understanding that you will consult both people while crafting your training plans and that another mentor will provide input into your development should suffice. **[At the very least, you should explicitly confirm with them that they are on board with the following two points]{.underline}**:

    -   At certain points in your training, you will be spending 1 full work day or ½ day per week in the clinic, as part of **Longitudinal Rounds**.

    -   **You are expected to do your qualifying exam and submit your fellowship grant earlier than your graduate school cohort**. Your PI should not think of you as an "entering graduate student" and should be oriented to the fact that both of these are now expected to happen **within** your first two years of graduate school.


-   **Is there funding for the projects that you are interested in? Can they be funded?** There are new ideas all the time in the lab - some stick but many don't. If you want to work on something, it\'s best that there be some sort of funding to support that project. This does not necessarily have to be a specific grant for your project (after all, you\'re supposed to write that), but the PI should have support for complementary, broader, or more comprehensive projects related to yours. This is where revisiting [[NIH RePORT]{.underline}](https://report.nih.gov/), [[NSF Award Search]{.underline}](https://www.nsf.gov/awardsearch/), or your prospective mentor\'s Biosketch would be helpful. If you have a specific idea that you\'ve been thinking about, it\'s probably worth asking them about which of their grants would support that work. **Also, double check their funding by looking up their grant history;** aside from the previous resources, two up-and-coming sources for grant information are [[Grantome.com](http://grantome.com/)]{.underline} and [[Dimensions.ai]{.underline}](https://www.dimensions.ai/). Always remember that **grants beget grants**. Your PI's track record with funding will be evaluated when you seek your own F30 funding and their expertise in grant writing should form the foundation of your own ability to write grants. Therefore, even if new projects are not expensive (i.e. you're just analyzing existing data or doing strictly computational work) your PI's grant funding record matters for your immediate and long term future.

-   **Conduct more sit-down or phone interviews. Speak to at least one person that is no longer a part of the lab.** Pretty much all aspects of what has been discussed so far (funding, schedules, workflow, writing and feedback) are fair game discussion points for anyone who was mentored or worked for a prospective mentor. **Additionally, try to get in touch with people who have left the lab; this includes those who graduated/got promoted as well as those who left under more negative circumstances.** As these individuals are no longer with the lab, they may speak more freely about it and have critical insight about how their experiences have molded their career. Finding these individuals (especially those who left the lab under less-than-ideal circumstances) can be difficult. Look on lab websites, look at the author lists on papers, and ask your network, which includes other MSTP students (you\'re always free to email one of us).

-   **Be honest with yourself: do you want to play for this team?** This is a much more abstract question, but it cuts to the heart of the relationship that you\'re building. When you\'re presenting your work, you are also a representative of your mentor and the kind of work that is going on in their lab. People see you through the lens by which they know your mentor and you will be expected to be a good ambassador of your mentor\'s ideas and previous scientific contributions. Additionally, for many people, the mentor-mentee relationship lasts well beyond the PhD - there are tenured faculty that still read drafts and give feedback on publications to their mentors. Even if you are not the best of friends, you are bound to this person in many ways, for longer than you think. No one is perfect and you should be tolerant of another\'s flaws, just as you will need tolerance of your own. Regardless, trust your gut when answering questions like: Is this a leader I can get behind? Are these the people I want to work with? Is this where I want to be for some time? These seem like soft questions, but they dictate your day-to-day drive more than any other aspect of the job.

-   **Have a word with Dr. O\'Banion before you make any commitments**. No amount of advice given to you by your peers can fully replace the perspective that Dr. O\'Banion has on success in this program. Considering that choosing a mentor is one of the most critical decisions you will make, you have everything to gain and nothing to lose by having a discussion with Dr. O\'Banion before finalizing a commitment.

## F30 Troubleshooting {-}

*Author: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu)*

The purpose of this article is to log solutions to unqiue **but not uncommon** problems that our students have encountered during the F30 submission process. Ideally, each problem has a short background and a detail of the steps taken to mitigate the issue. Please feel free to submit your experiences to the "Author", who is really tasked with keeping this article up to date.

### "Refresher" Training in Responsible Conduct of Research Needed for 5+ year PhDs: NOT-OD-10-019 Guidelines. {-}

Some of our students, when submitting proposals that include a 5 year PhD training time, have come across stubling block in the review process where by their Program Officer will inform them that they need refersher training for RCR that is compatible with [NOT-OD-10-019 Guidlines](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-10-019.html). For example, one might get a phrase in an email like: 

>"NIH requires that instruction must be undertaken at least once during each career stage, and at a frequency of no less than once every four years. This means that you are due for refresher training during the proposed project period."

Our general understanding is of these guidlines, gleaned through some student experience, is that after your initial RCR training in the first year of Graduate School, you are required to do a series of activities to continue your education in RCR such that every four years, you meet the requirements set forth in these guidelines. Some programs have all their 5+ year PhD students re-take the RCR course. We have found that Program Officers are willing to accept a table of continuing RCR activites that you have done or plan to do over the next 5 years that meet the requirements. 

It is recommended that you speak email Dr. O'Banion if this issue comes up. Additionally, if you choose to make a custom RCR plan (often the easier and more desireable route), be sure to have your Program Officer look it over before it is formally sent into the NIH. Finally, if you need an example for a customized plan and how it was presented, please feel free to contact [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu). 
