# Special Topics {-}

## Taxes {-}

*Author: [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu)*

### Taxes, in general... {-}

The guiding principle of taxation is that the government takes a portion of your income in order to fund the nation and its associated services (police, EMTs, etc.). In a "typical" job, your employer is responsible taking a portion of each of your paychecks and paying taxes on your behalf throughout the year (i.e. withholding income). The amount you earned from an employer and the amount withheld for a given year is reported to you and the government on a [W-2 form](https://www.irs.gov/forms-pubs/about-form-w-2). For people who have a job that issues a W-2 and that job is their only source of income, the process of paying taxes is essentially checking to make sure that your tax bill is paid in full from the money that was already withheld and asking for a tax refund if more money was paid than necessary.

### Taxes At University of Rochester are a "Fellowship" - not a W-2 {-}

For complicated reasons related to the nuances of tax law[^1], money given to students with scholarship stipends at the university (MSTP students, graduate students, etc.) is classified as "fellowship income". With fellowship income, you don't have a W-2 and you're not formally recognized as an employee, which means that withholding is **not done for you by default and YOU WILL HAVE TO DO THIS YOURSELF**. Hence, you are given your full check every two weeks (without money taken out and given to the government) and expected to calculate and pay your own tax bill. At the end of the year, you will be given a letter that states how much stipend money was disbursed to you, which will help you calculate what your income was for the year. For most MSTP students, this is their only source of income and it constitutes the entirety of the Adjusted Gross Income. 

Again, because you're not a W-2 employee, you're expected to make payments towards your tax bill in advance or throughout the year (i.e. [estimated tax payments](https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes)). In nutshell, the payment of estimated taxes requires you to make a good faith estimate of your tax bill for the upcoming year and pay 90% of that bill in advance. You can pay that estimated tax bill as a single lump payment when doing your taxes for the previous year (in April) or in four quarterly payments across the year. Calculating your estimated taxes will require that you use **Federal Form 1040-ES and NYS Form IT-2105-I** and the process is basically the process of calculating your tax bill. **Hence, it is recommneded that you calculate your estimated tax payments for the upcoming year each time you sit down to do your taxes for the previous year**. These forms can be a little technically dense, but contain all the information you would need and payments can be made instantaneously using online portals.

This tax "stuff" is not intuitive, so if you have questions or need help, be sure to contact Alysha Taggart, a Blue Book Editor, or get help from UMRC's Graduate Student Society, which maintains [a page of information on Graduate Student Taxes.](https://www.urmc.rochester.edu/education/graduate/current-students/graduate-student-society/tax-information-for-graduate-students.aspx)

### A Simple Approach to Estimated Tax Payments {-}

Based on current Federal and NYS Tax Brackets, I have personally found that cutting out $175 from each paycheck and putting it in a separate savings account is sufficient to cover my tax bills. Basically, I set up a separate account (savings, for the higher percentage) at my bank and automatically transfer $175 from each paycheck to the account. I estimate my tax bill each season (using those sheets) and pay my estimated tax payments to the Fed and NYS each quarter. Over the years, this account has generally grown every so slightly, which means I could probably reduce the $175 to $150. However, given the laundry list of things that we need to save for, it doesn't hurt to stash some extra cash away. 

If you're looking set up a bank account with a branch that is physically accessible to the medical center, the [URMC Student-To-Student Guide has section on local banks on page 49.](https://www.urmc.rochester.edu/medialibraries/urmcmedia/education/md/documents/bluebook.pdf)

### The Incoming Hiccup {-}

In your first year, you may transition from W-2 income at a previous job to fellowship income. **Thus, you will need to save the right amount of money from your stipend paychecks yourself, then pay it as part of your tax bill for that year.**  This means that you will probably take 10-15%[^2] of every stipend check and put that in a private savings account. When you do your taxes for the year in which you transitioned to medical school, you'll probably need to pay more than what was already withheld on your behalf because withholding was not done for your fall income. To illustrate such a situation, let's say that you had a W-2 job for six months, where you made $30,000. The next six months, you made roughly $15,000 in scholarship income at the MSTP. Of the $30,000 that you made, a certain amount was withheld already and it's been handed over the government. From the $15,000 that you made, nothing was withheld. And so, from your stipend checks, you should put away 15% and be ready to pay that in taxes. When tax season comes around, you will calculate your tax bill using an Adjusted Gross Income of $45,000 and subtract the money that was withheld already from the final bill. Because that withholding was only done for $30,000 out of your $45,000 total income, you will likely have a balance left to pay to the government. If you diverted 15% of your paychecks, then you should be able to pay that balance. For most people, the $175 out of every paycheck suggested above should work just fine, assuming your Adjusted Gross Income is between $25,000 and $60,000. 

[^1]: Thanks to new tax laws stipulating taxes on "fringe benefits" for jobs, the amount that a university pays in scholarships for employees is considered taxable income beyond ~$5,000 per year. This means that, if graduate students were considered to be employees, it is *very* possible that they would be taxed at the $80,000 income level, because the ~$50,000 tuition waiver would be considered a "fringe benefit". The move away from a W-2 thus fully shields graduate students from this (and probably still benefits the university, somehow). 

[^2]: This number is recommended based on the tax bracket that MSTP students are typically within. This might be higher or lower, depending on the amount of money you made in a job prior to entering the program. For example, someone transitioning from a $100,000/year job in the fall has probably already made enough money to be taxed at a higher rate. Accordingly, someone who did not work a job before the fall will probably not make enough money that year to qualify for any taxation at all. Check federal and state tax brackets for more information on this.
