# Reference {-}

## Student Council Minutes {-}

Links to recent student council minutes are provided here, in case you can't find that email :P

[2-2-20 Minutes](https://docs.google.com/document/d/1gIxQGDpXbK2rwJZiYExuOJTKea-ypwjiy4baL8bSroU)
[12-17-19 Minutes](https://docs.google.com/document/d/11KvmKkDxuw9oU082dASCgl1ZlzMjbAaCpIuSpp_nRa0/edit)


## Editors Notes {-}

This section is dedicated documentation for the editors of this blue book. It details the current goals and subproject that the editors are currently working on. It also describes the basic organization for oversight of this book and the workflows used by editors to produce content.

### Current Initiatives {-#current-inits}

**Finalize Advice Sections for M1 and M2 classes**. We would like to have *short* advice sections for M1 and M2 classes. This is mostly to cover aspects of advice that are not already addressed in the URMC Student to Student Guide. We invite ANY input for these topics and you can see the blank headings within the book. 

**Develop content for Pre-Qual Graduate School**. Content around transitions, doing so smoothly, and adressing MSTP specific topics is lacking in this book and in many other places. Right now, the following articles are lined up for pre-qual graduate school and are currently being worked on:

- Finding a Mentor (Uday and Keshov)
- Concise Approach to Writing and F30 (Annette and Keshov)
- Approach to Longitondal Clerkships (Keshov)

**Writing About Topics that Span Years**. We need some more people to pick up topics that across years, like buying a house, etc.

### Workflow {-}

#### Background Info {-}

We use [bookdown](https://bookdown.org/yihui/bookdown/) to produce this book, in its various forms, from Rmarkdown (.Rmd) files. The basic process is that Rmarkdown files (written using the [Markdown syntax](https://www.markdownguide.org/basic-syntax/)) are automatically compiled into an HTML website that is paginated like a book as well as an .Epub and PDF version of the book that can be downloaded from the website.

Each of the chapters (except the Preface which is part of index.rmd) exists as an independent .Rmd with a number before the chapter to designate it's order in the book. As such, level 1 headings designate a chapter and **level 2 headings designate an article under a chapter**. This last point is critical for content production.

When new content is produced using Microsoft Word or plain text, it ***THE HIGHEST HEADING LEVEL SHOULD BE LEVEL 2***. This ensures that when the content is converted to Markdown and pasted into the .rmd file, it shows up as an article under the correct chapter instead of a new chapter in the book. Any subheadings should be at level 3 or more to show up within the article. Pages are split at the level 1 and level 2 headings.

#### Process of editing {-}

In a nutshell, when not simply editing the plain text of an .Rmd file for minor errors, editors will:

- convert a Word document of content to Markdown
- paste this into the correct chapter
- ensure links and references render correctly
- make sure links line up (cross-linking, etc.)
- ensure that the website render's correctly
- push edits to the master branch

**It is the job of the ~~chump-in-charge~~ "senior" editor to review all pushes to the master branch and get approval for their integration from Alysha Taggart before accepting them.**

In the future, we are planning on having Alysha either create her own Github account to be the final check on this procees. Alternatively, the book in a more finalized form can be ported to the MSTP website. This is an ongoing conversation that we re-develop around May 2020.

#### Required R Packages and System Set-Ups {-}

- Install RStudio and Rmarkdown
- Ensure that you can use **Github** through RStudio or the command line.
- Download and install [Pandoc](https://pandoc.org/installing.html) which is a background utility used for converting between Markdown and other formats.
- Install Bookdown (preferably thorugh RStudio)
- Install DiagrammR (preferably through RStudio)

### Authorship {-}

As we are a bunch of academics, we technically have to provide some authorship guidelines for written work... right? Thus, the general authorship policy is as follows:

- Authorship is offered at the __Heading 3 level__ for the chapters "Early Medical Years" through "Special Topics", such that an author or authors are credited with the contents of everything under that heading. This basically means that people get credit for an "article" written under a "section" and "chapter" but we're only crediting the chapters that contain comprehensive writing (i.e. no authorship for bullet points on a Short Sheet)

- Authorship is depicted with the authors name displayed in their choice of style with a hyperlink to a legitimate method of contact. Usually, this would look something like [Keshov K. Sharma](mailto:keshov_sharma@urmc.rochester.edu) with the link opening to an email to the author. Twitter/Facebook links or links to Contact Me pages on a personal website are also acceptable.

- Authorship from a group of people is also acceptable, as long as there is at least one person who can be contacted. As such, "by [The MSTP Class of 2023](mailto:keshov_sharma@urmc.rochester.edu)" with the hyperlink pointing to Keshov K. Sharma's email is acceptable.

- Authorship should be granted to anyone who wrote a sizable portion of the current body text or significantly contributed to the formation of the current body text; but not to those who provided edits, suggestions, or minor corrections. If anyone really cares, authors should be lised in order of most contribution to least and, if need be, authorship and amount of contribution is decided by editors not involved in the authorship process of a particular contriubtion. As such, **when articles have been significantly revised by future years, original authors can be dropped by editors** to make space for those making more recent, sizable contributions to the current form of the book. 

- Authors have the option of switching between a credited and anonamymous contribution at any time. 

## Works Cited {-}
